### ISSUE TITLE
ERROR: readlink /var/lib/docker/overlay2: invalid argument

### ISSUE THREAD

**Issue by TurtleWolfe** [TurtleWolf/dockerLAMP#1]
I've been trying to follow this tutorial;
[How to create a docker-based LAMP stack using docker-compose on Ubuntu 18.04 Bionic Beaver Linux](https://linuxconfig.org/how-to-create-a-docker-based-lamp-stack-using-docker-compose-on-ubuntu-18-04-bionic-beaver-linux "Following this tutorial you will be able to create a LAMP environment using the Docker technology.")  
and I thought I understood it fairly well, but I'm getting an error I'm not sure what to do about.  
I can see the overlay referenced when I run `docker info`.  I've tried `pruning`, `removing`, `restrarting` docker, `restarting` windows.. tempted to delete all the containers next.

#### docker-compose.yml
```
version: '3'
services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            -  80:80
        volumes:
            - ./DocumentRoot:/var/www/html
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:10.1
        volumes:
          - mariadb:/var/lib/mysql
        environment:
          TZ: "Europe/Rome"
          MYSQL_ALLOW_EMPTY_PASSWORD: "no"
          MYSQL_ROOT_PASSWORD: "rootpwd"
          MYSQL_USER: 'testuser'
          MYSQL_PASSWORD: 'testpassword'
          MYSQL_DATABASE: 'testdb'

volumes:
    mariadb:
```
#### repo: [https://github.com/TurtleWolf/dockerLAMP](https://github.com/TurtleWolf/dockerLAMP "https://github.com/TurtleWolf/dockerLAMP") 
```
$ docker-compose up
```
### `ERROR: readlink /var/lib/docker/overlay2: invalid argument`  
![captureerror](https://user-images.githubusercontent.com/7327259/48442446-4545a600-e75c-11e8-99b8-ce029e13b466.PNG)
![capture](https://user-images.githubusercontent.com/7327259/48442445-4545a600-e75c-11e8-9173-4e4028caa4b5.PNG)
